name: main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-java@main
        with:
          distribution: temurin
          java-version: 11

      - uses: nttld/setup-ndk@main
        with:
          ndk-version: r21e

      - uses: krdlab/setup-haxe@v1.5.1
        with:
          haxe-version: 4.2.0
      # Runs a set of commands using the runners shell
      - name: haxe libs
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel 4.11.0
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons 2.11.0
          haxelib install tjson
          haxelib install hxjsonast
          haxelib git linc_luajit https://github.com/AndreiRudenko/linc_luajit
          haxelib install hscript
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hxcpp-debug-server
          haxelib list
      - name: run android
        run: haxelib run lime setup android
      - name: compile
        run: haxelib run lime build android
      - name: push
        uses: actions/upload-artifact@main
        with:
          name: build
          path: export/release/android/bin/app/build/outputs/apk/debu
